### ISSUE TITLE
ошибка в groups.py

### ISSUE THREAD

**Issue by d3f4u17** [galqiwi/vk-clones#1]
Если есть приватные группы, то выдаёт ошибку и крашит.
Вот тут исправлено чтобы пропускал такие группы

from time import sleep
from bots import vk_apis, zero_id, accounts, default_vk

groups = default_vk.groups.get(user_id=zero_id, count=100)

print(groups)

counter = 0
for vk in vk_apis:
	for group in groups['items']:
		try:
			print('add to', group)
			vk.groups.join(group_id=group)
		except Exception:
			counter += 1
			
	print(counter)
	counter += 1

ps спасибо за топовые исходники

**Comment by galqiwi** [comment]
Сорри за поздний ответ, я был оффлайн какое-то время. Приятно видеть, что кто-то использует твой код. Сейчас исправлю ошибку в мастере.
